// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6YuWkFaiLnyAkx1QI1vgia6Z0bb6D0o',
    appId: '1:1063755701166:web:d308f0ed777bfdd50e063f',
    messagingSenderId: '1063755701166',
    projectId: 'flutter-firebase-practice-2',
    authDomain: 'flutter-firebase-practice-2.firebaseapp.com',
    storageBucket: 'flutter-firebase-practice-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAIHfQdm_O6qI2WC7iQW9BV11Euu-YrQ',
    appId: '1:1063755701166:android:c8b5fe0e9b48a5190e063f',
    messagingSenderId: '1063755701166',
    projectId: 'flutter-firebase-practice-2',
    storageBucket: 'flutter-firebase-practice-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPw3dZ52v4orUUSw95rympuw9ZXKeY3pM',
    appId: '1:1063755701166:ios:9fb282dcd13f779c0e063f',
    messagingSenderId: '1063755701166',
    projectId: 'flutter-firebase-practice-2',
    storageBucket: 'flutter-firebase-practice-2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnectionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPw3dZ52v4orUUSw95rympuw9ZXKeY3pM',
    appId: '1:1063755701166:ios:9fb282dcd13f779c0e063f',
    messagingSenderId: '1063755701166',
    projectId: 'flutter-firebase-practice-2',
    storageBucket: 'flutter-firebase-practice-2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnectionFlutter',
  );
}
